### ISSUE TITLE
stripping span tags appears too agressive

### ISSUE THREAD

**Issue by timheilig** [vanilla/htmlawed#1]
If I pass

```html
<span style="expression(alert('XSS')">foo</span>
```

 into version 1.2.3 I end up getting back 

foo&lt;/span&gt;

This appears to be related to the following code:

            if ($e !== 'span' || !empty($a)) {
                if (!isset($cE[$e])) {
                    $q[] = $e;
                }
                echo '<', $e, $a, '>';
            }

If I take out the if ($e !== 'span' || !empty($a)) then it works as expected, returning

```
<span>foo</span>
```

**Comment by tburry** [comment]
The filter is intended to strip span tags that don't have any attributes. Your example includes an extra `</span>` which would be a bug. However, I can't seem to replicate it. Can you look at the code in my test and tell me what you've done differently?

https://github.com/vanilla/htmlawed/pull/2/files

**Comment by tburry** [comment]
Hey just pinging you again @timheilig to see if you have any additional information. See my previous comment.

**Comment by tburry** [comment]
Closing due to a lack of response.
