### ISSUE TITLE
Upgrade Htmlawed to 1.2.4

### ISSUE THREAD

**Issue by connerbw** [vanilla/htmlawed#17]
[Changelog](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s4.3)

Thanks.

**Comment by connerbw** [comment]
Related to #19

**Comment by DaazKu** [comment]
1.2.4 causes fatal errors if hl_spec is called 2 times.
I reported the issue. Waiting for upstream to be updated again.
