### ISSUE TITLE
Function create_function() is deprecated

### ISSUE THREAD

**Issue by connerbw** [vanilla/htmlawed#19]
When running tests on PHP nightlies in Travis CI (PHP 7.3.0-dev), we get:

> Function create_function() is deprecated
> vendor/vanilla/htmlawed/src/htmLawed/htmLawed.php:1010

~I will also submit an upstream issue.~

Edit: Fixed in 1.2.4 - 31 August 2017. Removes use of PHP 'create_function' function and '$php_errormsg' reserved variable (deprecated in PHP 7.2)

**Comment by DaazKu** [comment]
I already asked for it to be fixed on the upstream as you saw :)
I just need to find the time to do the update.

**Comment by DaazKu** [comment]
I'm going to close this issue since it will be resolved by #17
