### ISSUE TITLE
Question : initial tabulation ? 

### ISSUE THREAD

**Issue by cavo789** [vanilla/htmlawed#22]
Hello,

I found yesterday your repository after having searched for repo for htmLawed and found yours.

Did you know if it's possible to add an initial tabulation ? I didn't find something on http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm

My need / question : 

By using the code below

```php
$html= '<div><p>...</p></div>';
echo htmLawed($html, array('indent_size'=>4);
```

I receive 

```html
<div>
    <p>...</p>
</div>
```

i.e. the first tag has been put at column 0.

Is it possible to say, f.i. "First tag should be indented by two" like :

```html
        <div>
            <p>...</p>
        </div>
```

(this because when I read my HTML view source, I've my html and body tags f.i. well indented and the result of htmlLawed is put at column 0 and not at column 8 as, in fact, expected)

(htmlLawed is only used for the body part; not for the full HTML page).

Thanks !

**Comment by DaazKu** [comment]
I don't think is is possible.

You could always do that:
```php
$html= '<div><p>...</p></div>';
echo customIdentationFunction(htmLawed($html), 4);
```

**Comment by cavo789** [comment]
Yes of course 😉 but slower than a native property. Thanks for the answer.
