### ISSUE TITLE
Customized blockquote handling removes elements

### ISSUE THREAD

**Issue by greatislander** [vanilla/htmlawed#8]
It looks like the changes made to htmLawed's `<blockquote>` handling in this package have caused a regression in 2.2.

**Steps to Reproduce**

1. Pass the following HTML through `Htmlawed::filter()` with default configuration:

```
<blockquote>
  <p>Line 1</p>
  <p>Line 2</p>
  <p>Line 3</p>
</blockquote>
```

**Expected Result**

The markup is left unchanged.

**Actual Result**

The `<p>` tags are stripped from all but the first `<p>` within the blockquote.

```
<blockquote>
  <p>Line 1</p>
  Line 2
  Line 3
</blockquote>
```

**Comment by DaazKu** [comment]
Thank you for reporting this issue!

Unfortunately the unit tests won't pass if we put 'blockquote' back into $cb.
Adding it to $cF does the trick though!
